name: final_project_note_app
description: "A clean and modern note-taking app built with Flutter and Firebase."

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Application version: 1.0.0 and build number: 1
version: 1.0.0+1

# Specifies the minimum Dart SDK version required.
environment:
  sdk: ^3.7.0

# --------------------
# Main project dependencies
# --------------------
dependencies:
  flutter:
    sdk: flutter

  # Enables localization and internationalization features.
  flutter_localizations:
    sdk: flutter

  # Provides Cupertino-style icons (iOS-style).
  cupertino_icons: ^1.0.8

  # Core FlutterFire plugin. Must be initialized before using other Firebase services.
  firebase_core: ^3.12.1

  # Allows rendering of SVG files.
  flutter_svg: ^2.0.17

  # Firebase Authentication (email/password, Google, etc.).
  firebase_auth: ^5.5.1

  # Google sign-in support.
  google_sign_in: ^6.3.0

  # State management package (Provider pattern).
  provider: ^6.1.4

  # Internationalization and date formatting utilities.
  intl: 0.19.0

  # Cloud Firestore database integration.
  cloud_firestore: ^5.6.6

  # Allows defining custom HEX colors in your UI.
  hexcolor: ^3.0.1
  
  # Enables local key-value storage for persisting user preferences.
  shared_preferences: ^2.5.3


# --------------------
# Development dependencies (for testing and linting)
# --------------------
dev_dependencies:
  # Flutter's built-in testing framework.
  flutter_test:
    sdk: flutter

  # A package that provides recommended lints and best practices.
  flutter_lints: ^5.0.0

# --------------------
# Flutter-specific configuration
# --------------------
flutter:
  # Includes the Material Icons font.
  uses-material-design: true

  # Enables code generation for localization and other features.
  generate: true


  # Path to image assets used in the application.
  assets:
    - images/

  # Custom fonts configuration.
  fonts:
    - family: myFont
      fonts:
        - asset: fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: fonts/TitilliumWeb-Regular.ttf
        - asset: fonts/TitilliumWeb-Light.ttf

  # You can add more fonts here if needed.
flutter_intl:
  enabled: true
